-- Désactiver complètement RLS pour toutes les tables nécessaires
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE medias DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE engagements DISABLE ROW LEVEL SECURITY;
ALTER TABLE alerts DISABLE ROW LEVEL SECURITY;
